// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNCxjCaahOKJQ37QfnP415zvSTAi65vxs',
    appId: '1:696675160605:web:6847f77ba0d87c33a9ecf4',
    messagingSenderId: '696675160605',
    projectId: 'ce-mobile-b600c',
    authDomain: 'ce-mobile-b600c.firebaseapp.com',
    storageBucket: 'ce-mobile-b600c.appspot.com',
    measurementId: 'G-W7R2N57B1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsAzONHEnxcg7yn78z63xJQfmtp__dik',
    appId: '1:696675160605:android:edeed03959a0f0f7a9ecf4',
    messagingSenderId: '696675160605',
    projectId: 'ce-mobile-b600c',
    storageBucket: 'ce-mobile-b600c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJu9L-St7svqxBh3cBAWpmj_XlsGF6tJ4',
    appId: '1:696675160605:ios:03a0616839e748aaa9ecf4',
    messagingSenderId: '696675160605',
    projectId: 'ce-mobile-b600c',
    storageBucket: 'ce-mobile-b600c.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJu9L-St7svqxBh3cBAWpmj_XlsGF6tJ4',
    appId: '1:696675160605:ios:4a914032b8223161a9ecf4',
    messagingSenderId: '696675160605',
    projectId: 'ce-mobile-b600c',
    storageBucket: 'ce-mobile-b600c.appspot.com',
    iosBundleId: 'com.example.flutterDemo.RunnerTests',
  );
}
